import type { UeConsoleCommand } from './ueConsoleCommands'

export const PROJECT_BUILT_IN_CONSOLE_COMMAND_SOURCE = 'Survive 项目源码补充命令'

export const PROJECT_BUILT_IN_CONSOLE_COMMANDS: UeConsoleCommand[] = [
  {
    name: 'stat startfile',
    description: '开始录制标准 .ue4stats 文件；DefaultUAE.ini、GMScene.lua、UAEGameEngine.cpp 均有项目使用证据。',
    category: '性能录制',
    source: 'DefaultUAE.ini / GMScene.lua / UAEGameEngine.cpp',
    aliases: ['startfile', 'statsfile', '录制', '性能录制', 'ue4stats'],
  },
  {
    name: 'stat startfile <Filename>',
    insertText: 'stat startfile ',
    description: '开始录制标准 .ue4stats 文件，并指定相对文件名；UAEGameEngine.cpp 会拼接该形式。',
    category: '性能录制',
    source: 'UAEGameEngine.cpp',
    aliases: ['startfile filename', 'statsfile 文件名', '录制 文件名', 'ue4stats'],
  },
  {
    name: 'stat stopfile',
    description: '停止 statsfile 录制；DefaultUAE.ini、GMScene.lua、UAEGameEngine.cpp 均有项目使用证据。',
    category: '性能录制',
    source: 'DefaultUAE.ini / GMScene.lua / UAEGameEngine.cpp',
    aliases: ['stopfile', 'statsfile', '停止录制', '结束录制', 'ue4stats'],
  },
  {
    name: 'stat startfilelua',
    description: '项目扩展录制命令；相关知识卡确认它会录制 .ue4stats，并额外打开 lua.autostat。',
    category: '性能录制',
    source: 'PRE418 StatsFile knowledge card',
    aliases: ['startfilelua', 'lua autostat', 'lua 统计', '录制 lua'],
  },
  {
    name: 'stat startfilelua <Filename>',
    insertText: 'stat startfilelua ',
    description: '项目扩展录制命令；指定相对文件名并联动 Lua 统计。',
    category: '性能录制',
    source: 'PRE418 StatsFile knowledge card',
    aliases: ['startfilelua filename', 'lua autostat 文件名', '录制 lua 文件名'],
  },
  {
    name: 'stat startfilefilter -t=80.0 -c=3',
    description: '过滤录制高帧时数据；-t 为耗时阈值，-c 为命中次数。',
    category: '性能录制',
    source: 'PRE418 StatsFile knowledge card',
    aliases: ['startfilefilter', '过滤录制', '高帧录制', 'hitch 录制'],
  },
  {
    name: 'stat startfileraw',
    description: '录制原始 stats 数据，产物扩展名为 .ue4statsraw。',
    category: '性能录制',
    source: 'PRE418 StatsFile knowledge card',
    aliases: ['startfileraw', 'raw stats', '原始 stats'],
  },
  {
    name: 'netprofile enable',
    description: '开始录制 netprofile；DefaultUAE.ini、UGC GM 和 GMScene.lua 均有项目使用证据。',
    category: '性能录制',
    source: 'DefaultUAE.ini / GMScene.lua / public_gm.lua',
    aliases: ['网络录制', 'net profile', 'netprofile start', '录制 网络'],
  },
  {
    name: 'netprofile disable',
    description: '停止录制 netprofile；DefaultUAE.ini、UGC GM 和 GMScene.lua 均有项目使用证据。',
    category: '性能录制',
    source: 'DefaultUAE.ini / GMScene.lua / public_gm.lua',
    aliases: ['停止网络录制', 'net profile', 'netprofile stop'],
  },
  {
    name: 'stat fps',
    description: '显示 FPS；DSVideoRecorder 的调试流程会延迟执行该命令。',
    category: '性能观察',
    source: 'DSVideoRecorder GLiveAdaptor.cpp',
    aliases: ['fps', '帧率', '性能观察'],
  },
  {
    name: 'stat game',
    description: '显示 GameThread 统计；DSVideoRecorder 的调试流程会延迟执行该命令。',
    category: '性能观察',
    source: 'DSVideoRecorder GLiveAdaptor.cpp',
    aliases: ['game thread', '游戏线程', '性能观察'],
  },
  {
    name: 'stat unit',
    description: '显示 Game/Draw/GPU 帧耗时；项目工具里常用于性能观察。',
    category: '性能观察',
    source: 'Survive 性能排查常用命令',
    aliases: ['stat units', 'stats unit', 'stats units', 'unit', '帧耗时', '性能观察'],
  },
  {
    name: 'CsvCollectData',
    description: '项目注册命令：CsvCollectData setup/start/stop；CsvCollectDataReportStrategic.cpp 中注册。',
    category: '性能录制',
    source: 'CsvCollectDataReportStrategic.cpp',
    aliases: ['csv collect', 'csvcollectdata', 'csv 采集', '卡点上报'],
  },
  {
    name: 'CsvCollectData UserReportBug',
    description: '项目 Lua 中上报问题时会触发 CsvCollectData UserReportBug。',
    category: '性能录制',
    source: 'bp_report_bug.lua',
    aliases: ['bug 上报', 'csv collect bug', 'user report bug'],
  },
  {
    name: 'LS.ActivateConfig UGCDeveloperDefault',
    description: 'LiteStats 项目命令；UGCLiteStatsManager.cpp 会激活 UGCDeveloperDefault 配置。',
    category: '性能观察',
    source: 'UGCLiteStatsManager.cpp / LiteStatsUtils.cpp',
    aliases: ['litestats', 'LS.ActivateConfig', '激活 LiteStats', 'UGCDeveloperDefault'],
  },
  {
    name: 'LS.DeactivateConfig UGCDeveloperDefault',
    description: 'LiteStats 项目命令；UGCLiteStatsManager.cpp 会关闭 UGCDeveloperDefault 配置。',
    category: '性能观察',
    source: 'UGCLiteStatsManager.cpp / LiteStatsUtils.cpp',
    aliases: ['litestats', 'LS.DeactivateConfig', '关闭 LiteStats', 'UGCDeveloperDefault'],
  },
  {
    name: 'LS.TriggerHList',
    description: 'LiteStats 项目注册命令；LiteStatsUtils.cpp 中注册。',
    category: '性能观察',
    source: 'LiteStatsUtils.cpp',
    aliases: ['litestats', 'hlist', 'LiteStats 触发'],
  },
  {
    name: 'memreport -full',
    description: '完整内存报告；AutoRunTest、Lua 测试脚本中均有项目调用。',
    category: '内存与对象',
    source: 'AutoRunTest.cpp / mem_monitor.lua / bp_test_object.lua',
    aliases: ['内存', 'memory', 'memory report', '内存报告'],
  },
  {
    name: 'memreport -full -notgc',
    description: '完整内存报告但不先触发 GC；mem_monitor.lua 中有项目调用。',
    category: '内存与对象',
    source: 'mem_monitor.lua',
    aliases: ['内存', 'memory', 'memory report', '不 gc'],
  },
  {
    name: 'LuaMemReport',
    description: 'Lua 内存报告；GameFrontendHUD.cpp 和 DSHUD.cpp 均解析该命令。',
    category: '内存与对象',
    source: 'GameFrontendHUD.cpp / DSHUD.cpp',
    aliases: ['lua 内存', '内存', 'lua memory'],
  },
  {
    name: 'obj trygc',
    description: '尝试触发对象 GC；多个 Lua 更新/调试路径中调用。',
    category: '内存与对象',
    source: 'bp_versionupdate.lua / DebugerDogs debug_tool.lua',
    aliases: ['gc', '对象回收', '内存', 'trygc'],
  },
  {
    name: 'Obj Refs Name=<ObjectName>',
    insertText: 'Obj Refs Name=',
    description: '输出指定对象引用链；teamup、GM 调试 Lua 中有项目调用。',
    category: '内存与对象',
    source: 'bp_teamup_friend.lua / bp_umg_listinfo_item.lua',
    aliases: ['引用', 'refs', '对象引用', 'reference', 'Obj Refs Name'],
  },
  {
    name: 'FlushLog',
    description: '刷新日志；多个 GM/Lua 信息收集路径中调用。',
    category: '日志级别',
    source: 'GM_Log.lua / GM_CollectGameInfo.lua / bp_gm_activity.lua',
    aliases: ['日志', 'flush log', '刷新日志'],
  },
  {
    name: 'MoveTrace.Start',
    description: '项目注册命令：开始移动轨迹追踪。',
    category: '调试工具',
    source: 'Character movement MoveTrace registration',
    aliases: ['move trace', '移动追踪', '轨迹追踪'],
  },
  {
    name: 'MoveTrace.Stop',
    description: '项目注册命令：停止移动轨迹追踪。',
    category: '调试工具',
    source: 'Character movement MoveTrace registration',
    aliases: ['move trace', '移动追踪', '轨迹追踪'],
  },
  {
    name: 'MoveTrace.Status',
    description: '项目注册命令：查看移动轨迹追踪状态。',
    category: '调试工具',
    source: 'Character movement MoveTrace registration',
    aliases: ['move trace', '移动追踪', '轨迹追踪'],
  },
  {
    name: 'net.DetectUnrealNetwork',
    description: '项目注册网络检测命令；GameFrontendHUD.cpp 中注册。',
    category: '调试工具',
    source: 'GameFrontendHUD.cpp',
    aliases: ['网络检测', 'network detect', 'unreal network'],
  },
  {
    name: 'net.TestPacketLossRate',
    description: '项目注册丢包测试命令；GameFrontendHUD.cpp 中注册。',
    category: '调试工具',
    source: 'GameFrontendHUD.cpp',
    aliases: ['丢包', 'packet loss', '网络测试'],
  },
  {
    name: 'MemoryDetctor.PushCurrentMemoryData',
    description: '项目注册命令：推送当前内存数据；命令名按源码中的 Detctor 拼写保留。',
    category: '内存与对象',
    source: 'MemoryHelper.cpp',
    aliases: ['memory detector', '内存', '推送内存数据'],
  },
  {
    name: 'r.SetQualityPreset',
    description: '项目注册画质档位命令；WindowsGraphicsSettings.cpp 中注册，配置注释说明值范围 1-6。',
    category: '渲染画质',
    source: 'WindowsGraphicsSettings.cpp / DefaultWindowsGraphicsSettings.ini',
    aliases: ['画质', 'quality preset', '渲染', '图形设置'],
  },
  {
    name: 'r.SetQualityPreset <1-6>',
    insertText: 'r.SetQualityPreset ',
    description: '设置项目画质档位；DefaultWindowsGraphicsSettings.ini 注释说明 1-6 对应低到极致。',
    category: '渲染画质',
    source: 'DefaultWindowsGraphicsSettings.ini',
    aliases: ['画质', 'quality preset', '渲染', '图形设置'],
  },
  {
    name: 'r.DumpRenderSettingDependence',
    description: '项目注册命令：导出渲染设置依赖关系；WindowsScalability.cpp 中注册。',
    category: '渲染画质',
    source: 'WindowsScalability.cpp',
    aliases: ['渲染设置', 'dump render setting', '画质依赖'],
  },
]
