[Root:Survive]
Base=Survive
+Paths=Source
+Paths=Content
+ExpandChildren=Content

[Root:UE4181]
Base=UE4181
; 需要更新引擎目录时在这里追加，例如：
; +Paths=Engine\Source
; +ExpandChildren=Engine\Plugins

[Exclude]
+ChildDirs=.git
+ChildDirs=.svn
+ChildDirs=Saved
+ChildDirs=Intermediate
+ChildDirs=Binaries
+ChildDirs=DerivedDataCache
